export const ADD_ITEM = "ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const MODIFY_ITEM = "MODIFY_ITEM";
export const CLEAR_CART = "CLEAR_CART";
export const SET_SHIPPING_CHARGE = "SET_SHIPPING_CHARGE";
export const SET_SHIPPING_TYPE = "SET_SHIPPING_TYPE";
export const SET_TAX_VALUE = "SET_TAX_VALUE";
export const SET_COUPON_CODE_DISCOUNT_VALUE = "SET_COUPON_CODE_DISCOUNT_VALUE";
export const SET_CART = "SET_CART";
export const SET_CART_NULL_ITEM = "SET_CART_NULL_ITEM";
export const SET_CART_EDITABLE  = "SET_CART_EDITABLE";

//drawers
export const TOGGLE_CART_BAR = "TOGGLE_CART_BAR";
export const SHOW_CART_BAR = "SHOW_CART_BAR";export const HIDE_CART_BAR = "HIDE_CART_BAR";
export const TOGGLE_REGISTRATION_BAR = "TOGGLE_REGISTRATION_BAR";
export const SHOW_REGISTRATION_BAR = "SHOW_REGISTRATION_BAR";
export const HIDE_REGISTRATION_BAR = "HIDE_REGISTRATION_BAR";
export const HAS_LOGIN = "HAS_LOGIN";
export const TO_DISPLAY = "TO_DISPLAY";

export const SET_USER = "SET_USER";
export const UNSET_USER = "UNSET_USER";
export const SET_USER_META = "SET_USER_META";

export const SET_LOCATION = "SET_LOCATION";
export const SET_COUNTRY = "SET_COUNTRY";
export const SET_CONTINENT = "SET_CONTINENT";

export const SET_FAV_COUNTITY = "SET_FAV_COUNTITY";

export const SET_APUSER = "SET_APUSER";
export const UNSET_APUSER = "UNSET_APUSER";

export const SET_WISHLIST = "SET_WISHLIST";
export const UNSET_WISHLIST = "UNSET_WISHLIST";

export const SET_WISHLIST_LOGIN = "SET_WISHLIST_LOGIN";
export const UNSET_WISHLIST_LOGIN = "UNSET_WISHLIST_LOGIN";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_PRODUCT = "SET_PRODUCT";
export const CLEAR_PRODUCT = "CLEAR_PRODUCT";
export const SET_EXPRESS_CHECKOUT = "SET_EXPRESS_CHECKOUT";
export const SET_EXPRESS_PAYPAL_CHECKOUT = "SET_EXPRESS_PAYPAL_CHECKOUT";
export const SET_OD_FOR_PAYPAL = "SET_OD_FOR_PAYPAL";
export const SET_ORDER_FLAG = "SET_ORDER_FLAG";
export const SET_SP_PRODUCTS = "SET_SP_PRODUCTS";
export const SET_BILL_PLAN = "SET_BILL_PLAN";
export const SET_PAYPAL_FAIL = "SET_PAYPAL_FAIL";
export const SET_PAYPAL_SUCCESS = "SET_PAYPAL_SUCCESS";
export const CLEAR_PAYPAL_SUCCESS = "CLEAR_PAYPAL_SUCCESS";
export const HEADER_POP_UP_MODAL = "HEADER_POP_UP_MODAL";
export const SET_REFERRER = "SET_REFERRER";

export const SET_GUEST = "SET_GUEST";
export const SET_CHECKOUT_PAGE = "SET_CHECKOUT_PAGE";

export const SET_REDIRECT_CHECKOUT = "SET_REDIRECT_CHECKOUT";

// address
export const SET_ADDRESS = "SET_ADDRESS";

//cards
export const SET_CARDS = "SET_CARDS";

// reviews
export const GET_REVIEWS = "GET_REVIEWS";
export const CLEAR_REVIEWS = "CLEAR_REVIEWS";
export const REVIEW_POSTED = "REVIEW_POSTED";

// first setting
export const SET_ENTRY_MSG = "SET_ENTRY_MSG";

// menus
export const SHOW_SUB_MENU = "SHOW_SUB_MENU";
export const SET_SUB_MENU_PRODUCTS = "SET_SUB_MENU_PRODUCTS";
export const SET_ACTIVE_SUB_MENU = "SET_ACTIVE_SUB_MENU";
export const SET_LEARN_SUB_MENU = "SET_LEARN_SUB_MENU";
export const SET_POS_UP = "SET_POS_UP";

// errors
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_ERRORS = "SET_ERRORS";

// loading
export const LOADING = "LOADING";

// appointments
export const SET_CURRENT_APPOINTMENT = "SET_CURRENT_APPOINTMENT";
export const UNSET_CURRENT_APPOINTMENT = "UNSET_CURRENT_APPOINTMENT";