{
  /* <option value="ABeeZee">ABeeZee</option>
<option value="Abel">Abel</option>
<option value="Abhaya Libre">Abhaya Libre</option>
<option value="Abril Fatface">Abril Fatface</option>
<option value="Aclonica">Aclonica</option>
<option value="Acme">Acme</option>
<option value="Actor">Actor</option>
<option value="Adamina">Adamina</option>
<option value="Advent Pro">Advent Pro</option>
<option value="Aguafina Script">Aguafina Script</option>
<option value="Akronim">Akronim</option>
<option value="Aladin">Aladin</option>
<option value="Aldrich">Aldrich</option>
<option value="Alef">Alef</option>
<option value="Alegreya">Alegreya</option>
<option value="Alegreya SC">Alegreya SC</option>
<option value="Alegreya Sans">Alegreya Sans</option>
<option value="Alegreya Sans SC">Alegreya Sans SC</option>
<option value="Alex Brush">Alex Brush</option>
<option value="Alfa Slab One">Alfa Slab One</option>
<option value="Alice">Alice</option>
<option value="Alike">Alike</option>
<option value="Alike Angular">Alike Angular</option>
<option value="Allan">Allan</option>
<option value="Allerta">Allerta</option>
<option value="Allerta Stencil">Allerta Stencil</option>
<option value="Allura">Allura</option>
<option value="Almendra">Almendra</option>
<option value="Almendra Display">Almendra Display</option>
<option value="Almendra SC">Almendra SC</option>
<option value="Amarante">Amarante</option>
<option value="Amaranth">Amaranth</option>
<option value="Amatic SC">Amatic SC</option>
<option value="Amethysta">Amethysta</option>
<option value="Amiko">Amiko</option>
<option value="Amiri">Amiri</option>
<option value="Amita">Amita</option>
<option value="Anaheim">Anaheim</option>
<option value="Andada">Andada</option>
<option value="Andika">Andika</option>
<option value="Angkor">Angkor</option>
<option value="Annie Use Your Telescope">Annie Use Your Telescope</option>
<option value="Anonymous Pro">Anonymous Pro</option>
<option value="Antic">Antic</option>
<option value="Antic Didone">Antic Didone</option>
<option value="Antic Slab" */
}
